services:
  - type: web
    name: danyboy99-banking-system-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    repo: https://github.com/danyboy99/cv_chat_mcp
    branch: main
